### ISSUE TITLE
History

### ISSUE THREAD

**Issue by erica-zhong** [WRCWebmasters/WRC-Website#3]
#Goals
- Make information more readable 

#To-Do
- [ ] Separate history, traditions, and "today" into cards 
- [ ] Ask someone else to rewrite paragraphs to be more concise
- [ ] Format page like a timeline 
- [ ] Today section (pretty sure theres a poster in the commons with some will rice stats)

**Comment by caiismyname** [comment]
I was thinking, what if we combined the History and Traditions pages into one, and added a "today" section? In a sort of "This is our past, this is who we are now" manner. 

So, it'd flow kinda:
1. What WRC stands for
2. William Marsh Rice Jr. 
3. Traditions
4. Today ("by the numbers"?)

This would take some content work, probably with some history committee or what not, but I think it'd be more useful and cohesive than the current set up.

**Comment by erica-zhong** [comment]
@caiismyname that sounds like a great idea! are we going to do it like what you have on the a-team page where you can switch between Video/Text and have it be able to switch between the 4 tabs? otherwise that might be a really long page

**Comment by caiismyname** [comment]
I was thinking more like the "peer resources" one, where we fight the long-ness with the nav bar at the top. I'm thinking of this as a timeline.

**Comment by erica-zhong** [comment]
oh got it a timeline makes sense!
